# Generated by Django 4.2.4 on 2023-08-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_chat_is_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('prompt', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/img-topic/')),
                ('status', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
