# Generated by Django 4.2.4 on 2023-08-25 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Textimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/textimg/')),
                ('status', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='textimgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Textimg',
                'verbose_name_plural': 'Textimgs',
            },
        ),
    ]
