# Generated by Django 4.2.4 on 2023-08-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textimg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textimg',
            name='image',
        ),
        migrations.AddField(
            model_name='textimg',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
